export const makePermissions = [
  {
    id: 1,
    name: "Dashboard",
    checked: false,
    Nasted: [],
  },
  {
    id: 2,
    name: "Users",
    checked: false,
    Nasted: [],
  },
  {
    id: 3,
    name: "Games",
    checked: false,
    Nasted_call_size: 12,

    Nasted: [
      {
        id: 1,
        name: "Games Provider",
        checked: false,
      },
      {
        id: 2,
        name: "Games Setting",
        checked: false,
      },
      {
        id: 3,
        name: "Games Rates",
        checked: false,
      },
      {
        id: 4,
        name: "Games Result",
        checked: false,
      },
      {
        id: 5,
        name: "Games Revert",
        checked: false,
      },
      {
        id: 6,
        name: "Games Refund",
        checked: false,
      },
    ],
  },
  {
    id: 4,
    name: "Starline",
    checked: false,
    Nasted: [
      {
        id: 1,
        name: "Starline Provider",
        checked: false,
      },
      {
        id: 2,
        name: "Starline Setting",
        checked: false,
      },
      {
        id: 3,
        name: "Starline Rates",
        checked: false,
      },
      {
        id: 4,
        name: "Starline Result",
        checked: false,
      },
      {
        id: 5,
        name: "Starline Revert",
        checked: false,
      },
      {
        id: 6,
        name: "Starline Refund",
        checked: false,
      },
    ],
  },
  {
    id: 5,
    name: "Andar Bahar",
    checked: false,
    Nasted: [
      {
        id: 1,
        name: "Andar Bahar Provider",
        checked: false,
      },
      {
        id: 2,
        name: "Andar Bahar Setting",
        checked: false,
      },
      {
        id: 3,
        name: "Andar Bahar Rates",
        checked: false,
      },
      {
        id: 4,
        name: "Andar Bahar Result",
        checked: false,
      },
      {
        id: 5,
        name: "Andar Bahar Revert",
        checked: false,
      },
      {
        id: 6,
        name: "Andar Bahar Refund",
        checked: false,
      },
    ],
  },

  {
    id: 6,
    name: "Cutting Group",
    checked: false,
    Nasted: [],
  },
  {
    id: 7,
    name: "Bookie Corner",
    checked: false,
    Nasted: [
      {
        id: 1,
        name: "OC Cutting Group",
        checked: false,
      },
      {
        id: 2,
        name: "Final Cutting Group",
        checked: false,
      },
    ],
  },
  {
    id: 8,
    name: "Wallet",
    checked: false,
    Nasted: [
      {
        id: 1,
        name: "Fund Request",
        checked: false,
      },
      {
        id: 2,
        name: "ExportDebitReport",
        checked: false,
      },
      {
        id: 3,
        name: "View Wallet",
        checked: false,
      },
      {
        id: 4,
        name: "Request ON/OFF",
        checked: false,
      },
    ],
  },
  {
    id: 9,
    name: "Credit Request",
    checked: false,
    Nasted: [],
  },
  {
    id: 10,
    name: "Approved Debit Page",
    checked: false,
    Nasted: [
      {
        id: 1,
        name: "Paytm Request",
        checked: false,
      },
      {
        id: 2,
        name: "Bank Account Request",
        checked: false,
      },
    ],
  },
  {
    id: 11,
    name: "Pending Debit Request",
    checked: false,
    Nasted: [
      {
        id: 1,
        name: "Pending Bank Request",
        checked: false,
      },
      {
        id: 2,
        name: "Pending Paytm Request",
        checked: false,
      },
    ],
  },
  {
    id: 12,
    name: "Declined Request",
    checked: false,
    Nasted: [],
  },
  {
    id: 14,
    name: "Notification",
    checked: false,
    Nasted: [],
  },
  {
    id: 15,
    name: "News",
    checked: false,
    Nasted: [],
  },
  {
    id: 16,
    name: "Delete User",
    checked: false,
    Nasted: [],
  },
  {
    id: 17,
    name: "App Settings",
    checked: false,
    Nasted: [
      {
        id: 1,
        name: "How To Play",
        checked: false,
      },
      {
        id: 2,
        name: "Withdraw Screen",
        checked: false,
      },
      {
        id: 3,
        name: "Notice Board",
        checked: false,
      },
      {
        id: 4,
        name: "Wallet Contact",
        checked: false,
      },
      {
        id: 5,
        name: "App Version",
        checked: false,
      },
    ],
  },
  {
    id: 18,
    name: "Masters",
    checked: false,
    Nasted: [
      {
        id: 1,
        name: "Upi Id",
        checked: false,
      },
      {
        id: 2,
        name: "Add Fund Mode   ",
        checked: false,
      },
      {
        id: 3,
        name: "Manage Employee",
        checked: false,
      },
      {
        id: 4,
        name: "Create Employee",
        checked: false,
      },
    ],
  },
  {
    id: 19,
    name: "Reports",
    checked: false,
    Nasted: [
      {
        id: 1,
        name: "Jodi All",
        checked: false,
      },
      {
        id: 2,
        name: "Sales Report",
        checked: false,
      },
      {
        id: 3,
        name: "Andar Bahar Sales Report",
        checked: false,
      },
      {
        id: 4,
        name: "Andar Bahar Total Bids",
        checked: false,
      },
      {
        id: 5,
        name: "Fund Report",
        checked: false,
      },
      {
        id: 6,
        name: "Total Bids",
        checked: false,
      },
      {
        id: 7,
        name: "Ajay Sir Report",
        checked: false,
      },
      {
        id: 8,
        name: "Credit Debit Report",
        checked: false,
      },
      {
        id: 9,
        name: "Daily Report",
        checked: false,
      },
      {
        id: 10,
        name: "Bidding Report",
        checked: false,
      },
      {
        id: 11,
        name: "Customer Balance",
        checked: false,
      },
      {
        id: 12,
        name: "All User Bids",
        checked: false,
      },
      {
        id: 13,
        name: "Deleted Users",
        checked: false,
      },
      {
        id: 14,
        name: "Upi Fund Report",
        checked: false,
      },
    ],
  },
];



export const InitialValues = {
  Dashboard: false,
  Users: false,
  Games: false,
  "Games Provider": false,
  "Games Setting": false,
  "Games Rates": false,
  "Games Result": false,
  "Games Revert": false,
  "Games Refund": false,
  Starline: false,
  "Starline Provider": false,
  "Starline Setting": false,
  "Starline Rates": false,
  "Starline Result": false,
  "Starline Revert": false,
  "Starline Refund": false,
  "Starline Profit Loss": false,
  "Andar Bahar": false,
  "Andar Bahar Provider": false,
  "Andar Bahar Setting": false,
  "Andar Bahar Rates": false,
  "Andar Bahar Result": false,
  "Andar Bahar Revert": false,
  "Andar Bahar Refund": false,
  "AB Provider": false,
  "AB Setting": false,
  "AB Rates": false,
  "AB Profit Loss": false,
  "AB Result": false,
  "AB Revert": false,
  "AB Refund": false,
  "Cutting Group": false,
  "Bookie Corner": false,
  "OC Cutting Group": false,
  "Final Cutting Group": false,
  Wallet: false,
  "Fund Request": false,
  ExportDebitReport: false,
  "View Wallet": false,
  "Request ON/OFF": false,
  "Credit Request": false,
  "Approved Debit Page": false,
  "Paytm Request": false,
  "Bank Account Request": false,
  "Pending Debit Request": false,
  "Pending Bank Request": false,
  "Pending Paytm Request": false,
  "Declined Request": false,
  Notification: false,
  News: false,
  "Delete User": false,
  "App Settings": false,
  "How To Play": false,
  "Withdraw Screen": false,
  "Notice Board": false,
  "Profile Note": false,
  "Wallet Contact": false,
  "App Version": false,
  Masters: false,
  "Upi Id": false,
  "Add Fund Mode": false,
  "Manage Employee": false,
  "Create Employee": false,
  Reports: false,
  "Jodi All": false,
  "Sales Report": false,
  "Andar Bahar Sales Report": false,
  "Andar Bahar Total Bids": false,
  "Starline Sales Report": false,
  "Fund Report": false,
  "Total Bids": false,
  "Ajay Sir Report": false,
  "Credit Debit Report": false,
  "Daily Report": false,
  "Bidding Report": false,
  "Customer Balance": false,
  "All User Bids": false,
  "Deleted Users": false,
  "Upi Fund Report": false,
  Invoices: false,
};
